# <center>ATP PLAYER</center>

https://github.com/JeffSackmann/tennis_atp

http://www.tennisabstract.com/

https://libstore.ugent.be/fulltxt/RUG01/002/945/727/RUG01-002945727_2021_0001_AC.pdf

https://www.ultimatetennisstatistics.com/playerProfile?playerId=4920&tab=profile

## Imports

In [68]:
import os
import numpy as np
import pandas as pd

## Path

In [69]:
cwd = os.getcwd()

In [75]:
df = pd.read_csv(cwd + '/tennis_atp-master/atp_matches_2021.csv')
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,Frances Tiafoe,R,188.0,USA,23.493498,126952,NaN,NaN,Soon Woo Kwon,R,180.0,KOR,23.627652,6-3 6-2,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,Jan Lennard Struff,R,193.0,GER,31.233402,106329,NaN,NaN,Thiago Monteiro,L,183.0,BRA,27.134839,6-3 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,Sumit Nagal,R,NaN,IND,23.923340,104797,NaN,NaN,Denis Istomin,R,188.0,UZB,34.863792,6-4 6-7(6) 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,John Millman,R,183.0,AUS,32.095825,207518,NaN,NaN,Lorenzo Musetti,R,185.0,ITA,19.378508,6-3 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,Tomas Machac,R,NaN,CZE,20.763860,105311,NaN,NaN,Joao Sousa,R,185.0,POR,32.303901,6-7(5) 6-4 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0

In [76]:
df_under_50 = df[df['minutes'] <30]
df_under_50.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
81,2021-0308,Munich,Clay,32,A,20210426,291,105936,4.0,NaN,Filip Krajinovic,R,185.0,SRB,29.160849,105870,NaN,WC,Yannick Hanfmann,R,193.0,GER,29.451061,W/O,3,R16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0,1619.0,98.0,812.0
199,2021-0316,Bastad,Clay,32,A,20210712,297,134770,1.0,NaN,Casper Ruud,R,183.0,NOR,22.554415,105967,NaN,Q,Henri Laaksonen,R,185.0,SUI,29.281314,W/O,3,QF,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,2725.0,134.0,581.0
377,2021-0352,Paris Masters,Hard,64,M,20211101,281,200615,NaN,LL,Alexei Popyrin,R,196.0,AUS,22.242300,126774,3.0,NaN,Stefanos Tsitsipas,R,193.0,GRE,23.222450,4-2 RET,3,R32,27.0,1.0,1.0,14.0,11.0,11.0,1.0,3.0,0.0,0.0,2.0,0.0,28.0,19.0,11.0,4.0,3.0,2.0,3.0,71.0,912.0,3.0,7840.0
389,2021-0352,Paris Masters,Hard,64,M,20211101,293,104925,1.0,NaN,Novak Djokovic,R,188.0,SRB,34.447639,104792,15.0,NaN,Gael Monfils,R,193.0,FRA,35.167693,W/O,3,R16,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,10340.0,22.0,2078.0
480,2021-0403,Miami Masters,Hard,128,M,20210322,262,105138,7.0,NaN,Roberto Bautista Agut,R,183.0,ESP,32.936345,144750,NaN,NaN,Lloyd Harris,R,193.0,RSA,24.071184,W/O,3,R64,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,2910.0,52.0,1175.0

In [72]:
df_stop = df[df['score'].str.contains("W/O")|df['score'].str.contains("RET")]
df = df.drop(df_stop.index.values)

In [73]:
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,237,126207,NaN,NaN,Frances Tiafoe,R,188.0,USA,23.493498,126952,NaN,NaN,Soon Woo Kwon,R,180.0,KOR,23.627652,6-3 6-2,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,238,105526,NaN,NaN,Jan Lennard Struff,R,193.0,GER,31.233402,106329,NaN,NaN,Thiago Monteiro,L,183.0,BRA,27.134839,6-3 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,239,111576,NaN,NaN,Sumit Nagal,R,NaN,IND,23.923340,104797,NaN,NaN,Denis Istomin,R,188.0,UZB,34.863792,6-4 6-7(6) 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,240,105357,NaN,NaN,John Millman,R,183.0,AUS,32.095825,207518,NaN,NaN,Lorenzo Musetti,R,185.0,ITA,19.378508,6-3 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,241,207830,NaN,NaN,Tomas Machac,R,NaN,CZE,20.763860,105311,NaN,NaN,Joao Sousa,R,185.0,POR,32.303901,6-7(5) 6-4 6-4,3,R64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145.0,525.0,137.0,570.0

In [77]:
df = df.drop(['match_num','winner_seed','winner_entry','loser_seed','loser_entry','score','minutes','w_ace','w_df','w_svpt','w_1stIn','w_1stWon','w_2ndWon','w_SvGms','w_bpSaved','w_bpFaced','l_ace','l_df','l_svpt','l_1stIn','l_1stWon','l_2ndWon','l_SvGms','l_bpSaved','l_bpFaced'],axis=1)

In [78]:
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,winner_id,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,best_of,round,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,126207,Frances Tiafoe,R,188.0,USA,23.493498,126952,Soon Woo Kwon,R,180.0,KOR,23.627652,3,R64,53.0,1228.0,71.0,996.0
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,105526,Jan Lennard Struff,R,193.0,GER,31.233402,106329,Thiago Monteiro,L,183.0,BRA,27.134839,3,R64,48.0,1410.0,95.0,829.0
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,111576,Sumit Nagal,R,NaN,IND,23.923340,104797,Denis Istomin,R,188.0,UZB,34.863792,3,R64,160.0,471.0,197.0,354.0
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,105357,John Millman,R,183.0,AUS,32.095825,207518,Lorenzo Musetti,R,185.0,ITA,19.378508,3,R64,44.0,1476.0,61.0,1106.0
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,207830,Tomas Machac,R,NaN,CZE,20.763860,105311,Joao Sousa,R,185.0,POR,32.303901,3,R64,145.0,525.0,137.0,570.0

In [82]:
df_commun = df[['tourney_id','tourney_name','surface','draw_size','tourney_level','tourney_date','best_of','round']]
df_commun.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,best_of,round
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64

In [92]:
df_player1 = df[['winner_id','winner_name','winner_hand','winner_ht','winner_ioc','winner_age','winner_rank','winner_rank_points']]
df_player1 = df_player1.rename(columns={
    "winner_id": "player_id",
    "winner_name": "player_name",
    "winner_hand": "player_hand",
    "winner_ht": "player_ht",
    'winner_ioc': "player_ioc",
    'winner_age': "player_age",
    'winner_rank': "player_rank",
    'winner_rank_points': "player_rank_points"
})
df_player1['target'] = 'win'
df_player1.head()

,player_id,player_name,player_hand,player_ht,player_ioc,player_age,player_rank,player_rank_points,target
0,126207,Frances Tiafoe,R,188.0,USA,23.493498,53.0,1228.0,win
1,105526,Jan Lennard Struff,R,193.0,GER,31.233402,48.0,1410.0,win
2,111576,Sumit Nagal,R,NaN,IND,23.923340,160.0,471.0,win
3,105357,John Millman,R,183.0,AUS,32.095825,44.0,1476.0,win
4,207830,Tomas Machac,R,NaN,CZE,20.763860,145.0,525.0,win

In [93]:
df_player2 = df[['loser_id','loser_name','loser_hand','loser_ht','loser_ioc','loser_age','loser_rank','loser_rank_points']]
df_player2 = df_player2.rename(columns={
    "loser_id": "player_id",
    "loser_name": "player_name",
    "loser_hand": "player_hand",
    "loser_ht": "player_ht",
    'loser_ioc': "player_ioc",
    'loser_age': "player_age",
    'loser_rank': "player_rank",
    'loser_rank_points': "player_rank_points"
})
df_player2['target'] = 'lose'
df_player2.head()

,player_id,player_name,player_hand,player_ht,player_ioc,player_age,player_rank,player_rank_points,target
0,126952,Soon Woo Kwon,R,180.0,KOR,23.627652,71.0,996.0,lose
1,106329,Thiago Monteiro,L,183.0,BRA,27.134839,95.0,829.0,lose
2,104797,Denis Istomin,R,188.0,UZB,34.863792,197.0,354.0,lose
3,207518,Lorenzo Musetti,R,185.0,ITA,19.378508,61.0,1106.0,lose
4,105311,Joao Sousa,R,185.0,POR,32.303901,137.0,570.0,lose

In [96]:
df_c_p1 = df_commun.join(df_player1)
df_c_p1.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,best_of,round,player_id,player_name,player_hand,player_ht,player_ioc,player_age,player_rank,player_rank_points,target
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,126207,Frances Tiafoe,R,188.0,USA,23.493498,53.0,1228.0,win
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,105526,Jan Lennard Struff,R,193.0,GER,31.233402,48.0,1410.0,win
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,111576,Sumit Nagal,R,NaN,IND,23.923340,160.0,471.0,win
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,105357,John Millman,R,183.0,AUS,32.095825,44.0,1476.0,win
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,207830,Tomas Machac,R,NaN,CZE,20.763860,145.0,525.0,win

In [97]:
df_c_p2 = df_commun.join(df_player2)
df_c_p2.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,best_of,round,player_id,player_name,player_hand,player_ht,player_ioc,player_age,player_rank,player_rank_points,target
0,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,126952,Soon Woo Kwon,R,180.0,KOR,23.627652,71.0,996.0,lose
1,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,106329,Thiago Monteiro,L,183.0,BRA,27.134839,95.0,829.0,lose
2,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,104797,Denis Istomin,R,188.0,UZB,34.863792,197.0,354.0,lose
3,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,207518,Lorenzo Musetti,R,185.0,ITA,19.378508,61.0,1106.0,lose
4,2021-0096,Tokyo Olympics,Hard,64,A,20210724,3,R64,105311,Joao Sousa,R,185.0,POR,32.303901,137.0,570.0,lose

In [99]:
result = pd.concat([df_c_p1,df_c_p2])

In [104]:
result['tourney_date'] = pd.to_datetime(result['tourney_date'], format='%Y%m%d')
result = result.sort_values(by="tourney_date")
result.head(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,best_of,round,player_id,player_name,player_hand,player_ht,player_ioc,player_age,player_rank,player_rank_points,target
1169,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,144869,Tomas Martin Etcheverry,R,NaN,ARG,21.467488,256.0,216.0,lose
1173,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R16,106216,Bjorn Fratangelo,R,NaN,USA,27.463381,274.0,195.0,lose
1162,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,110536,Kevin King,U,NaN,USA,29.850787,304.0,154.0,lose
1168,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,126149,Gianluca Mager,R,185.0,ITA,26.094456,101.0,733.0,win
1167,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,105023,Sam Querrey,R,198.0,USA,33.245722,56.0,1065.0,win
1166,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,123755,Daniel Elahi Galan,R,191.0,COL,24.547570,115.0,606.0,win
1165,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,105933,Roberto Quiroz,L,193.0,ECU,28.865161,293.0,171.0,win
1164,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,103333,Ivo Karlovic,R,208.0,CRO,41.850787,148.0,444.0,win
1162,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,106216,Bjorn Fratangelo,R,NaN,USA,27.463381,274.0,195.0,win
1161,2021-0499,Delray Beach,Hard,32,A,2021-01-04,3,R32,111815,Cameron Norrie,L,188.0,GBR,25.368925,74.0,877.0,win

In [127]:
from sklearn.compose import make_column_transformer,make_column_selector
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Modèle
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [134]:
y = result['target'].replace(['win','lose'],[0,1])
X = result.drop(['target','tourney_date'],axis=1)

In [135]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [136]:
numerical_feature = make_column_selector(dtype_include=np.number)
categorical_feature = make_column_selector(dtype_exclude=np.number)

In [137]:
numerical_pipeline = make_pipeline(SimpleImputer(),StandardScaler())
categorical_pipeline = make_pipeline(SimpleImputer(strategy= 'most_frequent'),OneHotEncoder(handle_unknown = 'ignore'))

In [138]:
preprocessor = make_column_transformer((numerical_pipeline,numerical_feature),(categorical_pipeline,categorical_feature))

In [139]:
methods = [
    [
        RandomForestClassifier(random_state = 42),
        {
            "alg__max_depth" : [1,3,5,7,10],
            'alg__min_samples_leaf': [1,2,3,4,5]
        },
        'Random Forest',   
    ],
    [
        SVC(random_state = 42),
        {
            'alg__C': [0.1,1, 10, 100],
            'alg__gamma': [1,0.1,0.01,0.001],
            'alg__kernel': ['rbf', 'poly', 'sigmoid']
        },
        'SVC'
    ],
    [
        MLPClassifier(random_state = 42),
        {
            'alg__hidden_layer_sizes': [(10,30,10),(20,)],
            'alg__activation': ['tanh', 'relu'],
            'alg__solver': ['sgd', 'adam'],
            'alg__alpha': [0.0001, 0.05],
            'alg__learning_rate': ['constant','adaptive'],
            'alg__max_iter': [3000]
        },
        'Neural Network'
    ]
]
method, score_best, score_test = [],[],[]

# Recherche des meilleurs paramètres pour l'optimisation des algorithmes
for met in methods:
    model = Pipeline([
        ('pre',preprocessor),
        ('alg',met[0])
        ])
    grid = GridSearchCV(model,met[1],cv=5)
    grid.fit(X_train,y_train)
    print(met[2],'-\n    > Best score :',grid.best_score_,'\n    > Best params :',grid.best_params_,'\n    > Test score :',grid.score(X_test, y_test))
    method.append(met[2])
    score_best.append(grid.best_score_)
    score_test.append(grid.score(X_test, y_test))

Linear Regression -
    > Best score : -0.05047146602137174
    > Best params : {}
    > Test score : -0.03827236441888937
KNN -
    > Best score : 0.5608470737833264
    > Best params : {'alg__metric': 'euclidean', 'alg__n_neighbors': 49}
    > Test score : 0.538955087076077
Decision Tree -
    > Best score : 0.5750635791376357
    > Best params : {'alg__criterion': 'gini', 'alg__max_depth': 3, 'alg__min_samples_leaf': 4, 'alg__splitter': 'random'}
    > Test score : 0.5481209899175069
Random Forest -
    > Best score : 0.5846929285286422
    > Best params : {'alg__max_depth': 3, 'alg__min_samples_leaf': 3}
    > Test score : 0.5884509624197983
SVC -
    > Best score : 0.5849199218134241
    > Best params : {'alg__C': 1, 'alg__gamma': 0.01, 'alg__kernel': 'rbf'}
    > Test score : 0.5847846012832264

/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (3000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)

Neural Network -
    > Best score : 0.5817136416658786
    > Best params : {'alg__activation': 'tanh', 'alg__alpha': 0.0001, 'alg__hidden_layer_sizes': (20,), 'alg__learning_rate': 'adaptive', 'alg__max_iter': 3000, 'alg__solver': 'sgd'}
    > Test score : 0.5673693858845096

In [140]:
grid.fit(X_train,y_train)

/Users/charles/opt/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:573: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")